### ISSUE TITLE
Make the build based on git commit

### ISSUE THREAD

**Issue by tsunamistate** [flathub/org.diasurgical.DevilutionX#12]
Currently, I'm making a build based on the vendored archive of a release.

This has some advantages, but when a change is made upstream, I'm forced to patch the archive, while it would be so much easier to change the commit or git tag flatpak is based on.

This will require to declare and build all dependencies from manifest, which will make build longer

**Comment by AJenbo** [comment]
I don't understand the implications here, if it just takes longer then go for it, but somehow I feel that isn't the actually issue and some additional changes are required.

**Comment by tsunamistate** [comment]
This issue is just for me, but sure, I'll explain it

What I mean, is to refactor the manifest from using 

```yaml
sources:
      - type: archive
        url: https://github.com/diasurgical/devilutionX/releases/download/1.5.4/devilutionx-src-fully-vendored.tar.xz
```

to something like this:

```yaml
sources:
      - type: git
        commit: <sha256 of git commit>
```

This will remove the need for patches. If there's a change upstream I need to accomodate, I'll simply change the sha256 of a commit
I'll have to add some dependencies as modules, so they are built before DevX, so just RTFM for me :)
